package io.github.mgeladzerezo.miniorm.dialect;

import io.github.mgeladzerezo.miniorm.LockMode;
import io.github.mgeladzerezo.miniorm.error.MappingException;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Types;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import java.util.stream.Collectors;

/**
 * Everything that differs between databases. The default methods implement standard SQL; a
 * dialect overrides only where its database deviates. All identifiers passed in are raw names
 * and all SQL returned has them quoted.
 */
public interface Dialect {

    /**
     * Short name for logs and test output.
     *
     * @return for example {@code "postgresql"}
     */
    String name();

    /**
     * Quotes an identifier so reserved words ({@code user}, {@code order}) and mixed case are safe.
     *
     * @param identifier a raw table, column, index or sequence name
     * @return the quoted form
     */
    default String quote(String identifier) {
        return '"' + identifier.replace("\"", "\"\"") + '"';
    }

    // ------------------------------------------------------------------ DDL

    /**
     * DDL type for a column.
     *
     * @param databaseType one of {@code TypeRegistry.databaseTypes()}
     * @param length       length for strings; 0 means unbounded
     * @param precision    total digits for decimals
     * @param scale        fraction digits for decimals
     * @return the type as written in {@code CREATE TABLE}
     */
    default String columnType(Class<?> databaseType, int length, int precision, int scale) {
        if (databaseType == String.class) {
            return length > 0 ? "varchar(" + length + ")" : textType();
        }
        if (databaseType == BigDecimal.class) {
            return "numeric(" + precision + ", " + scale + ")";
        }
        if (databaseType == byte[].class) {
            return binaryType();
        }
        String type = STANDARD_TYPES.get(databaseType);
        if (type == null) {
            throw new MappingException("No DDL type for " + databaseType.getName());
        }
        return type;
    }

    /** Standard SQL type names for the fixed-size database types. */
    Map<Class<?>, String> STANDARD_TYPES = Map.ofEntries(
            Map.entry(Boolean.class, "boolean"),
            Map.entry(Short.class, "smallint"),
            Map.entry(Integer.class, "integer"),
            Map.entry(Long.class, "bigint"),
            Map.entry(Float.class, "real"),
            Map.entry(Double.class, "double precision"),
            Map.entry(LocalDate.class, "date"),
            Map.entry(LocalTime.class, "time"),
            Map.entry(LocalDateTime.class, "timestamp"),
            Map.entry(OffsetDateTime.class, "timestamp with time zone"),
            Map.entry(UUID.class, "uuid"));

    /**
     * Type for strings without a length limit.
     *
     * @return the DDL type
     */
    String textType();

    /**
     * Type for {@code byte[]} columns.
     *
     * @return the DDL type
     */
    String binaryType();

    /**
     * Clause appended to the column type of an identity primary key.
     *
     * @return for example {@code "generated by default as identity"}
     */
    default String identityClause() {
        return "generated by default as identity";
    }

    /**
     * Statement creating a sequence.
     *
     * @param name      raw sequence name
     * @param increment the allocation size
     * @return DDL
     */
    default String createSequence(String name, int increment) {
        return "create sequence if not exists " + quote(name) + " start with 1 increment by " + increment;
    }

    /**
     * The {@code java.sql.Types} codes that {@code DatabaseMetaData} may report for a column
     * of the given database type. Used by the schema validator.
     *
     * @param databaseType one of {@code TypeRegistry.databaseTypes()}
     * @return acceptable JDBC type codes
     */
    default Set<Integer> jdbcTypes(Class<?> databaseType) {
        if (databaseType == Boolean.class) {
            return Set.of(Types.BOOLEAN, Types.BIT);
        } else if (databaseType == Short.class) {
            return Set.of(Types.SMALLINT, Types.TINYINT);
        } else if (databaseType == Integer.class) {
            return Set.of(Types.INTEGER);
        } else if (databaseType == Long.class) {
            return Set.of(Types.BIGINT);
        } else if (databaseType == Float.class) {
            return Set.of(Types.REAL, Types.FLOAT);
        } else if (databaseType == Double.class) {
            return Set.of(Types.DOUBLE, Types.FLOAT);
        } else if (databaseType == BigDecimal.class) {
            return Set.of(Types.NUMERIC, Types.DECIMAL);
        } else if (databaseType == String.class) {
            return Set.of(Types.VARCHAR, Types.CHAR, Types.LONGVARCHAR, Types.CLOB, Types.NVARCHAR);
        } else if (databaseType == byte[].class) {
            return Set.of(Types.BINARY, Types.VARBINARY, Types.LONGVARBINARY, Types.BLOB);
        } else if (databaseType == LocalDate.class) {
            return Set.of(Types.DATE);
        } else if (databaseType == LocalTime.class) {
            return Set.of(Types.TIME);
        } else if (databaseType == LocalDateTime.class) {
            return Set.of(Types.TIMESTAMP);
        } else if (databaseType == OffsetDateTime.class) {
            return Set.of(Types.TIMESTAMP_WITH_TIMEZONE, Types.TIMESTAMP);
        } else if (databaseType == UUID.class) {
            return Set.of(Types.OTHER, Types.BINARY);
        }
        return Set.of();
    }

    // ------------------------------------------------------------------ DML

    /**
     * Appends the row-limiting clause to a SELECT and its bind values to {@code parameters},
     * in whatever order the clause needs them.
     *
     * @param sql        a complete SELECT without limit or offset
     * @param limit      maximum rows, or {@code null}
     * @param offset     rows to skip, or {@code null}
     * @param parameters bind values of the statement so far; limit and offset are added to it
     * @return the paginated SELECT
     */
    String paginate(String sql, Integer limit, Integer offset, List<Object> parameters);

    /**
     * Locking clause appended to a SELECT.
     *
     * @param mode requested lock
     * @return the clause with a leading space, or the empty string for {@link LockMode#NONE}
     */
    default String lockClause(LockMode mode) {
        return switch (mode) {
            case NONE -> "";
            case FOR_UPDATE -> " for update";
            case FOR_UPDATE_NOWAIT -> " for update nowait";
        };
    }

    /**
     * Whether an exception means "the row lock could not be obtained".
     *
     * @param e a driver exception
     * @return {@code true} for lock-not-available and lock-timeout errors
     */
    boolean isLockFailure(SQLException e);

    /**
     * Query returning the next value of a sequence as a single row with a single column.
     *
     * @param sequence raw sequence name
     * @return a SELECT
     */
    String sequenceNextValue(String sequence);

    /**
     * An insert-or-update statement with one {@code ?} per column, in column order.
     *
     * @param table      raw table name
     * @param columns    raw names of all columns being written
     * @param keyColumns raw names of the columns that identify an existing row
     * @return the upsert statement
     */
    String upsert(String table, List<String> columns, List<String> keyColumns);

    /**
     * Prepares an INSERT so that the database-generated key can be read from
     * {@code getGeneratedKeys()} afterwards, also after {@code executeBatch()}.
     *
     * @param connection the connection to prepare on
     * @param sql        the INSERT
     * @param idColumn   raw name of the identity column
     * @return the prepared statement
     * @throws SQLException if the driver rejects the statement
     */
    default PreparedStatement prepareInsert(Connection connection, String sql, String idColumn) throws SQLException {
        return connection.prepareStatement(sql, new String[] {idColumn});
    }

    /**
     * Quotes and comma-joins identifiers.
     *
     * @param identifiers raw names
     * @return for example {@code "a", "b"}
     */
    default String quoteAll(List<String> identifiers) {
        return identifiers.stream().map(this::quote).collect(Collectors.joining(", "));
    }
}
