package io.github.mgeladzerezo.miniorm;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import io.github.mgeladzerezo.miniorm.error.SchemaValidationException;
import io.github.mgeladzerezo.miniorm.support.Backend;
import io.github.mgeladzerezo.miniorm.support.TestDb;
import java.sql.Connection;
import java.sql.Statement;
import java.util.List;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.EnumSource;

/** DDL generation from metadata and the validator that diffs metadata against {@code DatabaseMetaData}. */
class SchemaTest {

    private static boolean enabled(Backend backend) {
        return System.getProperty("miniorm.backends", "h2,postgres").toLowerCase()
                .contains(backend.name().toLowerCase());
    }

    private static void execute(TestDb db, String sql) throws Exception {
        try (Connection connection = db.connection(); Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }

    @ParameterizedTest
    @EnumSource(Backend.class)
    void aFreshlyGeneratedSchemaValidatesAgainstItsOwnMetadata(Backend backend) throws Exception {
        org.junit.jupiter.api.Assumptions.assumeTrue(enabled(backend));
        try (TestDb db = TestDb.open(backend)) {
            assertThat(db.orm().schema().diff()).isEmpty();
            db.orm().schema().validate();
        }
    }

    @ParameterizedTest
    @EnumSource(Backend.class)
    void generatedDdlContainsTablesKeysSequencesAndIndexes(Backend backend) throws Exception {
        org.junit.jupiter.api.Assumptions.assumeTrue(enabled(backend));
        try (TestDb db = TestDb.open(backend)) {
            List<String> ddl = db.orm().schema().createStatements();
            String all = String.join("\n", ddl);
            assertThat(all).contains("create sequence if not exists \"purchase_order_seq\"")
                    .contains("increment by 10")
                    .contains("create table \"customer\"")
                    .contains("\"id\" bigint generated by default as identity primary key")
                    .contains("\"email\" varchar(255) not null unique")
                    .contains("\"street\" varchar(255)")
                    .contains("foreign key (\"customer_id\") references \"customer\" (\"id\")")
                    .contains("create index if not exists \"idx_customer_tier_name\"");
            // Referenced tables are created before the tables that reference them.
            assertThat(all.indexOf("create table \"customer\"")).isLessThan(all.indexOf("create table \"purchase_orders\""));
            // Foreign keys come after every table, which is what makes circular references possible.
            assertThat(all.lastIndexOf("create table")).isLessThan(all.indexOf("add constraint"));
        }
    }

    @ParameterizedTest
    @EnumSource(Backend.class)
    void theValidatorReportsEveryKindOfDrift(Backend backend) throws Exception {
        org.junit.jupiter.api.Assumptions.assumeTrue(enabled(backend));
        try (TestDb db = TestDb.open(backend)) {
            execute(db, "alter table \"customer\" drop column \"points\"");
            execute(db, "alter table \"product\" drop column \"name\"");
            execute(db, "alter table \"product\" add column \"name\" integer");
            execute(db, "alter table \"order_line\" drop constraint \"fk_order_line_product_id\"");
            execute(db, "drop table \"category\" cascade");

            List<String> problems = db.orm().schema().diff();
            assertThat(problems).anySatisfy(p -> assertThat(p).contains("customer.points").contains("missing"));
            assertThat(problems).anySatisfy(p -> assertThat(p).contains("product.name").contains("JDBC type"));
            assertThat(problems).anySatisfy(p -> assertThat(p).contains("order_line.product_id").contains("foreign key"));
            assertThat(problems).anySatisfy(p -> assertThat(p).contains("Table 'category'").contains("does not exist"));
            assertThatThrownBy(() -> db.orm().schema().validate()).isInstanceOf(SchemaValidationException.class)
                    .hasMessageContaining("problem(s)");
        }
    }

    @ParameterizedTest
    @EnumSource(Backend.class)
    void dropRemovesTheTablesAndSequences(Backend backend) throws Exception {
        org.junit.jupiter.api.Assumptions.assumeTrue(enabled(backend));
        try (TestDb db = TestDb.open(backend)) {
            db.orm().schema().drop();
            assertThat(db.orm().schema().diff()).hasSize(db.orm().metadata().all().size())
                    .allSatisfy(p -> assertThat(p).contains("does not exist"));
        }
    }
}
